[build]
  command = "npm run build"
  publish = "react-frontend/build"

[secrets_scan]
  omit_paths = [
    "react-frontend/public/images/*",
    "react-frontend/build/images/*",
    "react-frontend/build/static/js/*",
    "react-frontend/build/static/js/*.map",
    "react-frontend/src/*"
  ] 